version: "3.8"

services:
  intellect-frontend:
    container_name: intellect-frontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=3003
    ports:
      - "3003:3003"
    networks:
      - shared-app-network
    restart: unless-stopped

networks:
  shared-app-network:
    external: true
